/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IdType = "CC" | "CE" | "NIT";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type LocationType = "bodega" | "kiosk" | "tienda";

export type MoveType = "ADJUSTMENT" | "RECEIPT" | "RETURN" | "SALE" | "TRANSFER";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentMethod = "card" | "cash" | "credit" | "digital_wallet" | "hybrid" | "points";

export type PaymentTermsType = "CONTADO" | "CREDITO";

export type PointsTransactionType = "adjustment" | "bonus" | "earned" | "redeemed";

export type PurchaseOrderStatus = "cancelled" | "draft" | "received" | "sent";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CampaignProducts {
  campaignId: string;
  productId: number;
}

export interface CashMovements {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  direction: string;
  id: Generated<string>;
  reason: string | null;
  sessionId: string | null;
}

export interface CashSessions {
  closedAt: Timestamp | null;
  closingAmount: Generated<Numeric | null>;
  id: Generated<string>;
  openedAt: Generated<Timestamp>;
  openingAmount: Generated<Numeric | null>;
  userUuid: string | null;
}

export interface Categories {
  id: Generated<number>;
  name: string;
}

export interface ClockBreaks {
  endAt: Timestamp | null;
  id: Generated<string>;
  startAt: Timestamp;
  timeClockId: string | null;
}

export interface Coupons {
  code: string;
  createdAt: Generated<Timestamp | null>;
  currentUses: Generated<number | null>;
  customerId: number | null;
  expiresAt: Timestamp | null;
  isActive: Generated<boolean | null>;
  maxUses: number | null;
  promotionId: string | null;
}

export interface Customers {
  address: string | null;
  apartment: string | null;
  createdAt: Generated<Timestamp | null>;
  createdVia: Generated<string | null>;
  customerNumber: string;
  dateOfBirth: Timestamp | null;
  email: string | null;
  firstName: string | null;
  id: Generated<number>;
  idNumber: string | null;
  idType: string | null;
  isActive: Generated<boolean | null>;
  lastName: string | null;
  lifetimePoints: Generated<number | null>;
  locationId: number | null;
  mobile: string | null;
  name: string;
  notes: string | null;
  phone: string | null;
  pinEnabled: Generated<boolean | null>;
  pinHash: string | null;
  pinSetAt: Timestamp | null;
  tierId: Generated<number | null>;
  totalPoints: Generated<number | null>;
  updatedAt: Generated<Timestamp | null>;
  uuid: string | null;
}

export interface CustomerTiers {
  color: string | null;
  createdAt: Generated<Timestamp | null>;
  discountPercentage: Generated<Numeric>;
  icon: string | null;
  id: Generated<number>;
  minLifetimePoints: number;
  name: string;
  pointsMultiplier: Generated<Numeric>;
}

export interface Departments {
  id: Generated<number>;
  name: string;
}

export interface EmployeePositions {
  departmentId: number | null;
  effectiveFrom: Generated<Timestamp>;
  effectiveTo: Timestamp | null;
  employeeUuid: string;
  positionId: number;
}

export interface Employees {
  code: string | null;
  createdAt: Generated<Timestamp>;
  defaultLocationId: number | null;
  email: string | null;
  fullName: string;
  hireDate: Timestamp | null;
  phone: string | null;
  pinHash: string | null;
  status: Generated<string>;
  uuid: Generated<string>;
}

export interface Holidays {
  date: Timestamp;
  name: string;
}

export interface Kiosks {
  createdAt: Generated<Timestamp | null>;
  deviceCode: string;
  deviceIdentifier: string | null;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  lastSeenAt: Timestamp | null;
  locationId: number;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface LeaveRequests {
  approvedBy: string | null;
  createdAt: Generated<Timestamp>;
  employeeUuid: string | null;
  endsAt: Timestamp;
  id: Generated<string>;
  notes: string | null;
  startsAt: Timestamp;
  status: Generated<string>;
  type: string;
}

export interface Locations {
  address: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  locationType: Generated<LocationType>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface LoginAttempts {
  attemptedAt: Timestamp | null;
  email: string;
  id: Generated<number>;
  success: boolean;
}

export interface LoyaltyCampaigns {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  endDate: Timestamp;
  id: string;
  isActive: Generated<boolean | null>;
  name: string;
  pointsMultiplier: Generated<Numeric | null>;
  startDate: Timestamp;
}

export interface LoyaltySettings {
  description: string | null;
  id: Generated<number>;
  settingKey: string;
  settingValue: Numeric;
  updatedAt: Generated<Timestamp | null>;
}

export interface Modules {
  code: string;
  id: Generated<number>;
  name: string;
}

export interface OvertimeRules {
  dailyThresholdMinutes: Generated<number>;
  effectiveFrom: Generated<Timestamp>;
  effectiveTo: Timestamp | null;
  holidayMultiplier: Generated<Numeric>;
  id: Generated<number>;
  nightEnd: Generated<string>;
  nightMultiplier: Generated<Numeric>;
  nightStart: Generated<string>;
  weeklyThresholdMinutes: Generated<number>;
}

export interface PasswordResetTokens {
  expiresAt: Timestamp;
  token: Generated<string>;
  usedAt: Timestamp | null;
  userUuid: string;
}

export interface Payments {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  method: string;
  transactionId: number | null;
}

export interface PayPeriods {
  closedAt: Timestamp | null;
  endDate: Timestamp;
  id: Generated<string>;
  schedule: Generated<string>;
  startDate: Timestamp;
}

export interface Permissions {
  id: Generated<number>;
  name: string;
}

export interface Pods {
  createdAt: Generated<Timestamp | null>;
  id: Generated<string>;
  photoUrl: string | null;
  signedBy: string | null;
  stopId: string | null;
}

export interface PointsTransactions {
  createdAt: Generated<Timestamp | null>;
  customerId: number;
  description: string | null;
  expiresAt: Timestamp | null;
  id: Generated<number>;
  pointsAmount: number;
  processedBy: string | null;
  referenceNumber: string | null;
  transactionId: number | null;
  transactionType: PointsTransactionType;
}

export interface PosEquipment {
  code: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  locationId: number;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Positions {
  id: Generated<number>;
  name: string;
}

export interface Productlocationparams {
  daysofcovertarget: number | null;
  id: Generated<number>;
  locationid: number;
  productid: number;
  safetystock: Numeric | null;
}

export interface ProductLots {
  expiresOn: Timestamp | null;
  id: Generated<string>;
  lotCode: string | null;
  productUuid: string;
}

export interface ProductPrices {
  channel: string | null;
  createdAt: Generated<Timestamp | null>;
  effectiveFrom: Generated<Timestamp>;
  effectiveTo: Timestamp | null;
  id: Generated<number>;
  locationId: number | null;
  price: Numeric;
  productId: number;
}

export interface Products {
  barcode: string | null;
  category: string | null;
  categoryId: number | null;
  cost: Generated<Numeric | null>;
  createdAt: Generated<Timestamp | null>;
  daysofcovertarget: number | null;
  description: string | null;
  id: Generated<number>;
  imageurl: string | null;
  isActive: Generated<boolean>;
  maxqty: Numeric | null;
  minimumStock: Generated<number>;
  minqty: Numeric | null;
  name: string;
  preferredSupplierId: number | null;
  price: Numeric;
  promotionalLabel: string | null;
  reorderenabled: Generated<boolean | null>;
  sku: string | null;
  stockQuantity: Generated<number>;
  subcategoryId: number | null;
  supplierId: number | null;
  updatedAt: Generated<Timestamp | null>;
  uuid: string | null;
}

export interface PromotionCategories {
  categoryId: number;
  promotionId: string;
}

export interface PromotionLocations {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  locationId: number | null;
  promotionId: string | null;
}

export interface PromotionProducts {
  isRequired: Generated<boolean | null>;
  productId: number;
  promotionId: string;
}

export interface Promotions {
  appliesToAllLocations: Generated<boolean | null>;
  buyQuantity: number | null;
  createdAt: Generated<Timestamp | null>;
  currentUses: Generated<number | null>;
  daysOfWeek: number[] | null;
  description: string | null;
  discountAmount: Numeric | null;
  discountPercentage: Numeric | null;
  endDate: Timestamp;
  endTime: string | null;
  getQuantity: number | null;
  id: string;
  isActive: Generated<boolean | null>;
  maxTotalUses: number | null;
  maxUsesPerCustomer: number | null;
  minQuantity: number | null;
  name: string;
  priority: Generated<number | null>;
  promotionType: string;
  startDate: Timestamp;
  startTime: string | null;
}

export interface PromotionTypes {
  code: string;
  description: string | null;
  name: string;
}

export interface PromotionUsage {
  couponCode: string | null;
  customerId: number | null;
  discountApplied: Numeric;
  id: Generated<number>;
  promotionId: string | null;
  transactionId: number | null;
  usedAt: Generated<Timestamp | null>;
}

export interface PurchaseOrderItems {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  poId: number;
  productId: number;
  qty: number;
  taxRate: Generated<Numeric | null>;
  unitPrice: Numeric;
  updatedAt: Generated<Timestamp | null>;
}

export interface PurchaseOrders {
  createdAt: Generated<Timestamp | null>;
  expectedDate: Timestamp | null;
  id: Generated<number>;
  locationId: number | null;
  notes: string | null;
  status: Generated<PurchaseOrderStatus | null>;
  subtotal: Generated<Numeric | null>;
  supplierId: number;
  tax: Generated<Numeric | null>;
  total: Generated<Numeric | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Reordersuggestions {
  createdat: Generated<Timestamp | null>;
  currentstock: Numeric | null;
  demanddaily: Numeric | null;
  id: Generated<number>;
  leadtimedays: number | null;
  locationid: number;
  productid: number;
  rop: Numeric | null;
  safetystock: Numeric | null;
  status: Generated<string>;
  suggestedqty: Numeric;
  supplierid: number | null;
  targetstock: Numeric | null;
}

export interface Rolemodule {
  canread: Generated<boolean | null>;
  canwrite: Generated<boolean | null>;
  modulecode: string;
  roleid: number;
}

export interface RoleModule {
  canRead: Generated<boolean | null>;
  canWrite: Generated<boolean | null>;
  moduleCode: string;
  roleId: number;
}

export interface RolePermission {
  permissionId: number;
  roleId: number;
}

export interface Roles {
  description: string | null;
  id: Generated<number>;
  name: string;
}

export interface Routes {
  date: Timestamp | null;
  id: Generated<string>;
  status: string | null;
  vehicleId: number | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  issuedAt: Timestamp | null;
  lastAccessed: Generated<Timestamp>;
  revokedAt: Timestamp | null;
  userUuid: string;
}

export interface ShiftAssignments {
  employeeUuid: string;
  shiftId: string;
}

export interface Shifts {
  breakMinutes: Generated<number>;
  createdAt: Generated<Timestamp>;
  endsAt: Timestamp;
  id: Generated<string>;
  locationId: number | null;
  published: Generated<boolean>;
  role: string | null;
  startsAt: Timestamp;
}

export interface StockMovements {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  locationId: number | null;
  lotId: string;
  productId: number | null;
  productUuid: string;
  qty: Numeric;
  reason: string | null;
  ref: string | null;
  type: MoveType;
}

export interface Stops {
  address: string | null;
  id: Generated<string>;
  orderNo: number | null;
  routeId: string | null;
  status: string | null;
  windowFrom: Timestamp | null;
  windowTo: Timestamp | null;
}

export interface Subcategories {
  categoryId: number | null;
  id: Generated<number>;
  name: string;
}

export interface Suppliers {
  address: string | null;
  contactPerson: string | null;
  createdAt: Generated<Timestamp | null>;
  creditDays: number | null;
  defaultLocationId: number | null;
  email: string | null;
  id: Generated<number>;
  idType: Generated<IdType | null>;
  isActive: Generated<boolean>;
  leadTimeDays: number | null;
  name: string;
  notes: string | null;
  paymentTermsType: Generated<PaymentTermsType | null>;
  phone: string | null;
  taxId: string | null;
  updatedAt: Generated<Timestamp | null>;
  uuid: string | null;
}

export interface TimeClocks {
  clockInAt: Timestamp | null;
  clockOutAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  employeeUuid: string | null;
  id: Generated<string>;
  locationId: number | null;
  notes: string | null;
  source: Generated<string>;
}

export interface TimesheetEntries {
  id: Generated<string>;
  minutesHoliday: Generated<number>;
  minutesNight: Generated<number>;
  minutesOvertime: Generated<number>;
  minutesRegular: Generated<number>;
  timesheetId: string | null;
  workDate: Timestamp;
}

export interface Timesheets {
  approvedAt: Timestamp | null;
  employeeUuid: string | null;
  id: Generated<string>;
  periodId: string | null;
  status: Generated<string>;
  submittedAt: Timestamp | null;
}

export interface TransactionItems {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  productId: number;
  quantity: number;
  transactionId: number;
  unitPrice: Numeric;
}

export interface Transactions {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  locationId: number | null;
  paymentMethod: PaymentMethod;
  totalAmount: Numeric;
}

export interface UserRole {
  roleId: number;
  userUuid: string;
}

export interface Users {
  address: string | null;
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  dateofbirth: Timestamp | null;
  displayName: string | null;
  email: string;
  fullName: string | null;
  id: Generated<number>;
  identificationnumber: string | null;
  identificationtype: string | null;
  isActive: Generated<boolean>;
  passwordHash: string;
  phone: string | null;
  position: string | null;
  role: Generated<string>;
  status: Generated<string>;
  uuid: Generated<string>;
}

export interface Vehicles {
  capacity: number | null;
  id: Generated<number>;
  name: string | null;
}

export interface WageRates {
  currency: Generated<string>;
  effectiveFrom: Generated<Timestamp>;
  effectiveTo: Timestamp | null;
  employeeUuid: string | null;
  id: Generated<string>;
  kind: Generated<string>;
  rateCents: Int8;
}

export interface DB {
  campaignProducts: CampaignProducts;
  cashMovements: CashMovements;
  cashSessions: CashSessions;
  categories: Categories;
  clockBreaks: ClockBreaks;
  coupons: Coupons;
  customers: Customers;
  customerTiers: CustomerTiers;
  departments: Departments;
  employeePositions: EmployeePositions;
  employees: Employees;
  holidays: Holidays;
  kiosks: Kiosks;
  leaveRequests: LeaveRequests;
  locations: Locations;
  loginAttempts: LoginAttempts;
  loyaltyCampaigns: LoyaltyCampaigns;
  loyaltySettings: LoyaltySettings;
  modules: Modules;
  overtimeRules: OvertimeRules;
  passwordResetTokens: PasswordResetTokens;
  payments: Payments;
  payPeriods: PayPeriods;
  permissions: Permissions;
  pods: Pods;
  pointsTransactions: PointsTransactions;
  posEquipment: PosEquipment;
  positions: Positions;
  productlocationparams: Productlocationparams;
  productLots: ProductLots;
  productPrices: ProductPrices;
  products: Products;
  promotionCategories: PromotionCategories;
  promotionLocations: PromotionLocations;
  promotionProducts: PromotionProducts;
  promotions: Promotions;
  promotionTypes: PromotionTypes;
  promotionUsage: PromotionUsage;
  purchaseOrderItems: PurchaseOrderItems;
  purchaseOrders: PurchaseOrders;
  reordersuggestions: Reordersuggestions;
  rolemodule: Rolemodule;
  roleModule: RoleModule;
  rolePermission: RolePermission;
  roles: Roles;
  routes: Routes;
  sessions: Sessions;
  shiftAssignments: ShiftAssignments;
  shifts: Shifts;
  stockMovements: StockMovements;
  stops: Stops;
  subcategories: Subcategories;
  suppliers: Suppliers;
  timeClocks: TimeClocks;
  timesheetEntries: TimesheetEntries;
  timesheets: Timesheets;
  transactionItems: TransactionItems;
  transactions: Transactions;
  userRole: UserRole;
  users: Users;
  vehicles: Vehicles;
  wageRates: WageRates;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const PaymentMethodArrayValues: [PaymentMethod, ...PaymentMethod[]] = ["card","cash","credit","digital_wallet","hybrid","points"];
export const PurchaseOrderStatusArrayValues: [PurchaseOrderStatus, ...PurchaseOrderStatus[]] = ["cancelled","draft","received","sent"];
export const PointsTransactionTypeArrayValues: [PointsTransactionType, ...PointsTransactionType[]] = ["adjustment","bonus","earned","redeemed"];
export const MoveTypeArrayValues: [MoveType, ...MoveType[]] = ["ADJUSTMENT","RECEIPT","RETURN","SALE","TRANSFER"];
export const IdTypeArrayValues: [IdType, ...IdType[]] = ["CC","CE","NIT"];
export const PaymentTermsTypeArrayValues: [PaymentTermsType, ...PaymentTermsType[]] = ["CONTADO","CREDITO"];
export const LocationTypeArrayValues: [LocationType, ...LocationType[]] = ["bodega","kiosk","tienda"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.